sudo: false

arch: amd64
os:
  - linux
  - osx
dist: bionic # minimum version supported for now.

language: rust

rust:
  - stable

addons:
  apt:
    packages: # recommanded versions for rust-bindgen
      - r-base-dev
      - llvm-3.9-dev
      - libclang-3.9-dev

env: # specify the clang path for rust-bindgen
  - LIBCLANG_PATH=/usr/lib/llvm-3.9/lib

script:
  - cargo build
  - cargo test -- --nocapture --test-threads=1

  
